version: "3.9"

services:
  db:
    container_name: mysql_db
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=atc
    - MYSQL_CHARACTER_SET_SERVER=utf8mb4
    - MYSQL_COLLATION_SERVER=utf8mb4_unicode_ci

    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql

  app:
    container_name: atc_app
    build: app
    depends_on:
      - db
    ports:
      - "8000:8000"